/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#005e97',
        'primary-container': '#0077be',
        'primary-fixed': '#cfe5ff',
        'primary-fixed-dim': '#9acbff',
        'on-primary': '#ffffff',
        'on-primary-container': '#f7f9ff',
        secondary: '#78582f',
        'secondary-container': '#fed39f',
        'secondary-fixed': '#ffddb7',
        'secondary-fixed-dim': '#eabf8d',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#795930',
        'on-secondary-fixed': '#2a1700',
        tertiary: '#555b61',
        'tertiary-container': '#6d737a',
        'on-tertiary': '#ffffff',
        surface: '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'surface-variant': '#e2e2e2',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#404751',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f0f1f1',
        outline: '#707882',
        'outline-variant': '#c0c7d2',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        background: '#f9f9f9',
        'on-background': '#1a1c1c',
      },
      fontFamily: {
        headline: ['Heebo', 'Assistant', 'sans-serif'],
        body: ['Assistant', 'Inter', 'sans-serif'],
        label: ['Assistant', 'Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.625rem',
        sm: '0.375rem',
        md: '0.75rem',
        lg: '0.875rem',
        xl: '1.25rem',
        '2xl': '1.75rem',
        '3xl': '2.5rem',
        full: '9999px',
      },
      boxShadow: {
        monolith: '0 24px 40px -8px rgba(26, 28, 28, 0.06)',
        glow: '0 8px 32px rgba(0, 94, 151, 0.2)',
      }
    },
  },
  plugins: [],
}
